package humanit.error;

public enum ErrorCode {
    CLIENT_NOT_FOUND,
    DOCUMENT_NOT_FOUND,
    CLIENT_EMAIL_EXISTS,
    CLIENT_TAX_IDENTIFIER_EXISTS,
    DOCUMENT_NUMBER_EXISTS,
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    DATA_INTEGRITY_VIOLATION,
    INTERNAL_SERVER_ERROR,
    INVALID_CREDENTIALS,
    USER_EMAIL_EXISTS
}
