CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    tax_identifier VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,

    CONSTRAINT uk_clients_tax_identifier UNIQUE (tax_identifier),
    CONSTRAINT uk_clients_email UNIQUE (email)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    number VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    expiration_date DATE NOT NULL,

    CONSTRAINT fk_documents_client
        FOREIGN KEY (client_id)
        REFERENCES clients(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_documents_client_number
        UNIQUE (client_id, number)
);